import fs from 'fs'
import path from 'path'
import jsonc from 'jsonc-parser'
import { projectRoot } from './utils/env.ts'
import prettier from 'prettier'

const settingsPath = path.join(projectRoot, '.vscode', 'settings.json')
const excludes = [
	// == prettier break ==
	'.claude',
	'.cursor',
	'.env*',
	'.github',
	'.storybook',
	// 'backend/**',
	'dist/',
	'docs/',
	'node_modules/',
	'public/',
	// 'temp/',
	'.gitignore',
	'.prettierignore',
	'CLAUDE.md',
	'components.json',
	'eslint.config.js',
	'package-lock.json',
	'prettier.config.js',
	'README.md',
	'tsconfig.app.json',
	'tsconfig.json',
	'tsconfig.node.json',
	'vite.config.ts',
	'vitest.shims.d.ts',
].sort()

/**
 * vscode文件隐藏
 *
 * 一键聚焦模式，方便快速阅读代码
 */
async function toggleFocus() {
	if (!fs.existsSync(settingsPath)) {
		console.warn('.vscode/settings.json not found')
		return
	}

	const content = fs.readFileSync(settingsPath, 'utf-8')
	const settings = jsonc.parse(content) || {}
	const hasExclude = settings['files.exclude']

	let edits: jsonc.Edit[]
	if (hasExclude) {
		// 恢复默认配置
		edits = jsonc.modify(content, ['files.exclude'], undefined, {})
		console.log('🟢 已恢复文件显示')
	} else {
		// 隐藏文件
		const excludeMap: Record<string, boolean> = {}
		excludes.forEach((item) => (excludeMap[item] = true))
		edits = jsonc.modify(content, ['files.exclude'], excludeMap, {})
		console.log('👀 已隐藏部分文件')
	}

	const updated = jsonc.applyEdits(content, edits)
	const formatEdits = jsonc.format(updated, undefined, { tabSize: 2, insertSpaces: true })
	let output = jsonc.applyEdits(updated, formatEdits)

	// 添加一段注释
	if (!hasExclude) {
		const comment = `// ===== 🤖 Auto-generated by toggle-focus-vcs =====`
		// string replace "files.exclude" -> "$comments\n"file.exl

		output = output.replace('"files.exclude"', `${comment}\n"files.exclude"`)

		// prettier
		output = await prettier.format(output, { parser: 'json' })
	}

	fs.writeFileSync(settingsPath, output)
}

toggleFocus()
