package services

import (
	"ai-models-backend/internal/models"
	"fmt"
	"time"
	"math/rand"
	"strings"
)

// AI 服务
type AIService struct {
}
func NewAIService() *AIService {
	return &AIService{}
}

// 处理聊天请求
func (s *AIService) Chat(userID uint, req models.ChatRequest) (*models.ChatResponse, error) {
	time.Sleep(100 * time.Millisecond)
	
	response := &models.ChatResponse{
		ID:        fmt.Sprintf("chat_%d_%d", userID, time.Now().UnixNano()),
		Message:   s.generateMockResponse(req.Message),
		Model:     s.getModelName(req.Model),
		CreatedAt: time.Now(),
		Usage: models.Usage{
			PromptTokens:     len(strings.Fields(req.Message)),
			CompletionTokens: 50,
			TotalTokens:      len(strings.Fields(req.Message)) + 50,
		},
	}

	s.saveChatHistory(userID, "user", req.Message, req.Model)
	s.saveChatHistory(userID, "assistant", response.Message, req.Model)

	return response, nil
}

// 流式聊天
func (s *AIService) StreamChat(userID uint, req models.ChatRequest, responseChan chan<- string) error {
	
	mockResponse := s.generateMockResponse(req.Message)
	words := strings.Fields(mockResponse)
	
	for _, word := range words {
		select {
		case responseChan <- word + " ":
			time.Sleep(50 * time.Millisecond) // Simulate streaming delay
		default:
			return fmt.Errorf("channel closed")
		}
	}

	s.saveChatHistory(userID, "user", req.Message, req.Model)
	s.saveChatHistory(userID, "assistant", mockResponse, req.Model)

	return nil
}

// 文本生成
func (s *AIService) Generate(userID uint, req models.GenerateRequest) (*models.GenerateResponse, error) {
	time.Sleep(200 * time.Millisecond)
	
	response := &models.GenerateResponse{
		ID:        fmt.Sprintf("gen_%d_%d", userID, time.Now().UnixNano()),
		Content:   s.generateMockContent(req.Prompt),
		Model:     s.getModelName(req.Model),
		CreatedAt: time.Now(),
		Usage: models.Usage{
			PromptTokens:     len(strings.Fields(req.Prompt)),
			CompletionTokens: 100,
			TotalTokens:      len(strings.Fields(req.Prompt)) + 100,
		},
	}

	return response, nil
}

// 获取可用模型
func (s *AIService) GetAvailableModels() ([]models.AIModel, error) {
	
	models := []models.AIModel{
		{
			ID:          "gpt-3.5-turbo",
			Name:        "GPT-3.5 Turbo",
			Description: "Fast and efficient language model for chat and text generation",
			Provider:    "OpenAI",
			Type:        "chat",
			Capabilities: []string{"text-generation", "chat", "code-generation"},
			MaxTokens:   4096,
			IsActive:    true,
		},
		{
			ID:          "gpt-4",
			Name:        "GPT-4",
			Description: "Most capable language model with advanced reasoning",
			Provider:    "OpenAI",
			Type:        "chat",
			Capabilities: []string{"text-generation", "chat", "code-generation", "analysis"},
			MaxTokens:   8192,
			IsActive:    true,
		},
		{
			ID:          "claude-3-sonnet",
			Name:        "Claude 3 Sonnet",
			Description: "Balanced model for various tasks",
			Provider:    "Anthropic",
			Type:        "chat",
			Capabilities: []string{"text-generation", "chat", "analysis", "code-generation"},
			MaxTokens:   4096,
			IsActive:    true,
		},
		{
			ID:          "llama-2-70b",
			Name:        "Llama 2 70B",
			Description: "Open-source large language model",
			Provider:    "Meta",
			Type:        "completion",
			Capabilities: []string{"text-generation", "chat"},
			MaxTokens:   2048,
			IsActive:    true,
		},
	}

	return models, nil
}

// 获取聊天历史
func (s *AIService) GetChatHistory(userID uint, sessionID string) ([]models.ConversationHistory, error) {
	
	history := []models.ConversationHistory{
		{
			ID:        1,
			UserID:    userID,
			SessionID: sessionID,
			Role:      "user",
			Content:   "Hello, how are you?",
			Model:     "gpt-3.5-turbo",
			CreatedAt: time.Now().Add(-10 * time.Minute),
		},
		{
			ID:        2,
			UserID:    userID,
			SessionID: sessionID,
			Role:      "assistant",
			Content:   "Hello! I'm doing well, thank you for asking. How can I help you today?",
			Model:     "gpt-3.5-turbo",
			CreatedAt: time.Now().Add(-9 * time.Minute),
		},
	}

	return history, nil
}

// 清除聊天历史
func (s *AIService) ClearChatHistory(userID uint, sessionID string) error {
	return nil
}


func (s *AIService) generateMockResponse(message string) string {
	responses := []string{
		"That's an interesting question! Let me think about that.",
		"I understand what you're asking. Here's my perspective on that.",
		"Thank you for sharing that with me. I'd be happy to help.",
		"That's a great point. Let me elaborate on that topic.",
		"I can help you with that. Here's what I know about this subject.",
	}
	
	return responses[rand.Intn(len(responses))] + " " + 
		   "This is a mock response based on your message: \"" + message + "\""
}

func (s *AIService) generateMockContent(prompt string) string {
	return "This is generated content based on your prompt: \"" + prompt + "\". " +
		   "In a real application, this would be generated by an AI model with sophisticated " +
		   "natural language processing capabilities."
}

func (s *AIService) getModelName(model string) string {
	if model == "" {
		return "gpt-3.5-turbo"
	}
	return model
}

func (s *AIService) saveChatHistory(userID uint, role, content, model string) {
	sessionID := fmt.Sprintf("session_%d", userID)
	
	history := models.ConversationHistory{
		UserID:    userID,
		SessionID: sessionID,
		Role:      role,
		Content:   content,
		Model:     model,
		CreatedAt: time.Now(),
	}
	
	_ = history
}