name: Deploy Backend

on:
  # NOTE: 目前仅支持手动触发，防止频繁部署
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

# 设置权限
permissions:
  contents: read

concurrency:
  group: 'backend-deploy'
  cancel-in-progress: true # 取消正在运行的部署

jobs:
  # 后端部署作业
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      # Docker 配置
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_REGISTRY_VPC: ${{ secrets.DOCKER_REGISTRY_VPC }}
      DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # 服务器配置
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      # 日志控制
      VERBOSE: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend
        run: npm run deploy:be
        env:
          NODE_ENV: production