name: Deploy Backend

on:
  # NOTE: 目前仅支持手动触发，防止频繁部署
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master]
  workflow_dispatch:

# 设置权限
permissions:
  contents: read

concurrency:
  group: 'backend-deploy'
  cancel-in-progress: true # 取消正在运行的部署

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      SECRETS_KEY: ${{ secrets.SECRETS_KEY }}
      VERBOSE: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Decrypt secrets
        run: npm run secrets:decrypt

      - name: Prepare CI/CD environment
        run: npm run secrets:cicd

      - name: Fix SSH key permissions
        run: |
          if [ -f ~/.ssh/id_rsa ]; then
            chmod 600 ~/.ssh/id_rsa
            echo "✅ SSH key permissions fixed"
          else
            echo "⚠️ SSH key not found at ~/.ssh/id_rsa"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy Backend
        run: npm run deploy:be
